name: Robert Hunsberger
favicon: null
layout_spectrum: 0.49592
typography_spectrum: 0.16932
title: Robert Hunsberger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00cc99'
    - '#3396fb'
    - '#9900cc'
    - '#00ff01'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
