name: Robert Husnberger
favicon: null
layout_spectrum: 0.5763350389897823
typography_spectrum: 0.20195036428049207
title: Robert Hunsberger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00cc99'
    - '#3396fb'
    - '#9900cc'
    - '#00ff01'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
